// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxxxhnueygvtqkwlnwqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4eHhobnVleWd2dHFrd2xud3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA4NDksImV4cCI6MjA2NTQ5Njg0OX0.awqoqZAYUKX4vy9wKcRYVi-ivqpnlErh5E_HlP-3ieM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);